### ISSUE TITLE
[FEATURE] AutoFrame Dupe

### ISSUE THREAD

**Issue by cow167** [nukiz/3arthh4ck-continued#10]
can you check this code

package me.earth.earthhack.impl.modules.misc.framedupe;

import me.earth.earthhack.api.module.Module;
import me.earth.earthhack.api.module.util.Category;
import me.earth.earthhack.api.setting.Setting;
import me.earth.earthhack.api.setting.settings.BooleanSetting;
import me.earth.earthhack.api.setting.settings.NumberSetting;
import me.earth.earthhack.impl.util.client.SimpleData;
import net.minecraft.entity.Entity;
import net.minecraft.entity.item.EntityItemFrame;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemShulkerBox;
import net.minecraft.util.EnumHand;

public class AutoFrameDupe extends Module {
    protected Setting<Boolean> shulkersonly =
            register(new BooleanSetting("Shulkers Only", true));

    private NumberSetting<Integer> range =
            register(new NumberSetting<>("Range", 5, 0, 6));
    public NumberSetting<Integer> turns =
            register(new NumberSetting<>("Turns", 1, 0, 3));

    private NumberSetting<Integer> ticks =
            register(new NumberSetting<>("Ticks", 10, 1, 20));

        private int timeout_ticks = 0;

    public AutoFrameDupe() {
        super("AutoFrameDupe", Category.Misc);
        this.setData(new SimpleData(this,
                "op"));
    }
    @Override
    public void update() {
        if (mc.player != null && mc.world != null) {

            if (shulkersonly.getValue() != true) {
                int shulker_slot = getShulkerSlot();
                if (shulker_slot != -1) {
                    mc.player.inventory.currentItem = shulker_slot;
                }
            }

            for (Entity frame : mc.world.loadedEntityList) {
                if (frame instanceof EntityItemFrame) {
                    if (mc.player.getDistance(frame) <= range.get_value(1)) {
                        if (timeout_ticks >= ticks.get_value(1)) {
                            if (((EntityItemFrame) frame).getDisplayedItem().getItem() == Items.AIR && !mc.player.getHeldItemMainhand().isEmpty()) {
                                mc.playerController.interactWithEntity(mc.player, frame, EnumHand.MAIN_HAND);
                            }
                            if (((EntityItemFrame) frame).getDisplayedItem().getItem() != Items.AIR) {
                                for (int i = 0; i < turns.get_value(1); i++) {
                                    mc.playerController.interactWithEntity(mc.player, frame, EnumHand.MAIN_HAND);
                                }
                                mc.playerController.attackEntity(mc.player, frame);
                                timeout_ticks = 0;
                            }
                        }
                        ++timeout_ticks;
                    }
                }
            }

        }
    }

    private int getShulkerSlot() {
        int shulker_slot = -1;
        for (int i = 0; i < 9; i++) {
            Item item = mc.player.inventory.getStackInSlot(i).getItem();
            if (item instanceof ItemShulkerBox) shulker_slot = i;
        }
        return shulker_slot;
    }

}

**Comment by xyzbtw** [comment]
that code is fine

**Comment by nukiz** [comment]
It's fine. You could've just put that into yours, build it and test it though?

**Comment by cow167** [comment]
> It's fine. You could've just put that into yours, build it and test it though?
I did, but for some reasons it didn't work. that's why I upload this for u

**Comment by xyzbtw** [comment]
Are you sure you added it into the module manager?

> > It's fine. You could've just put that into yours, build it and test it though?
> > I did, but for some reasons it didn't work. that's why I upload this for u

**Comment by cow167** [comment]
> Are you sure you added it into the module manager?
> 
> > > It's fine. You could've just put that into yours, build it and test it though?
> > > I did, but for some reasons it didn't work. that's why I upload this for u

yes

**Comment by cow167** [comment]
> As xyzbtw said, if its not in the ModuleManager it won't be usable in the client. Did you do that?

Highly sure that it was added
