### ISSUE TITLE
[BUG]sneakcheck

### ISSUE THREAD

**Issue by AlexanderJonny** [nukiz/3arthh4ck-continued#11]
not working...

**Comment by AlexanderJonny** [comment]
![N}9~C96IDR{HDRJR%9APZNM](https://user-images.githubusercontent.com/92873946/225881756-d1d10659-fe69-476d-835a-53b7b58906e9.png)
I tried to modify the sneakcheck and now it works

**Comment by nukiz** [comment]
that's a better way of doing it, i was kinfa tired while making it but it wotked for me so i committed it

**Comment by nukiz** [comment]
should work now, let me know though
