### ISSUE TITLE
is it save?

### ISSUE THREAD

**Issue by X-Sergio-X** [nukiz/3arthh4ck-continued#15]
**Describe the bug**  

**To Reproduce**  

**Expected behavior**  
A clear and concise description of what you expected to happen. If your bug is a crash or something you don't need to fill this in.

**Crashlog**  
If you crashed and you don't provide a crashlog I will ignore you!

**Additional context**  

**Checklist**
- [x] I know how to properly use check boxes.
- [ ] I have included logs, screenshots, exceptions and / or steps to reproduce the issue.
- [ ] I followed the issue template.

**Comment by X-Sergio-X** [comment]
is it save?

**Comment by xyzbtw** [comment]
yes it's safe

**Comment by nukiz** [comment]
Yes it is safe. If you don't trust it, you shouldn't use it.
