### ISSUE TITLE
[FEATURE] Add Blocker

### ISSUE THREAD

**Issue by 0xSharkyy** [nukiz/3arthh4ck-continued#16]
This could be done by checking if one of the players surround blocks is broken by an entity that is not that player, then if the block is broken, toggle surround if it isn't already on, and place another block on top of the block that was broken by the enemy entity or the block that had to be replaced.

**Comment by xyzbtw** [comment]
LMAO

**Comment by nukiz** [comment]
This is implemented in Ai_2473's 3arthh4ck continuation, and this project was merged with his. It'll be released sooner or later, no ETA though.

**Comment by xyzbtw** [comment]
No way you actually made it work

**Comment by SeZal666** [comment]
WORK FOR POJAV?
