### ISSUE TITLE
[BUG]Speed-Instant Lshift's issues

### ISSUE THREAD

**Issue by AlexanderJonny** [nukiz/3arthh4ck-continued#9]
When I press Lshift, speed does not slow down,when i use speed-instant mode 
If speed is not slowed down by pressing Lshift, it will cause lagback.
You can try in 2b2tpvp.net (or other strict server), set the speed to instant and hold Lshift, move forward a distance, then you can find the problem

**Comment by xyzbtw** [comment]
nukiz you could just add this check into speed instant 
if (mc.player.isSneaking() || KeyBoardUtil.isKeyDown(mc.gameSettings.keyBindSneak)) return;
